project_id = "brydkxrudzrxwxfjndgt"

[functions.send-verification-email]
verify_jwt = false

[functions.send-workspace-request]
verify_jwt = false

[functions.approve-workspace-request]
verify_jwt = false

[functions.reject-workspace-request]
verify_jwt = false

[functions.invite-project-user]
verify_jwt = false

[functions.upload-dataset]
verify_jwt = false

[functions.dataset-status]
verify_jwt = false
